create database MODELO
use MODELO

CREATE TABLE T_CATEGORIA(
	
	COD_CATEGORIA CHAR(9) PRIMARY KEY ,
	NOMBRE_CATEGORIA VARCHAR(50) NULL,
	FECHA DATETIME DEFAULT GETDATE() NULL,
	USUARIO VARCHAR(5) NULL
)


CREATE TABLE T_PRODUCTO(
	
	COD_PRODUCTOS CHAR(9) PRIMARY KEY ,
	COD_CATEGORIA CHAR(9), 
	NOMBRE_PRODUCTO VARCHAR(50) NULL,
	CANTIDAD NUMERIC(8,2) NULL,
	FECHA DATETIME DEFAULT GETDATE() NULL,
	USUARIO VARCHAR(5) NULL,
	FOREIGN KEY (COD_CATEGORIA) REFERENCES T_CATEGORIA(COD_CATEGORIA)
)

CREATE TABLE T_USUARIO(
COD_USUARIO VARCHAR(5) PRIMARY KEY,
NOMBRE_USURIO VARCHAR(80),
CONTRASENIA VARCHAR(15)
)

CREATE TABLE T_PERSONAL(
COD_PERSONAL VARCHAR(7) PRIMARY KEY,
NOM_PERSONAL VARCHAR(80) NULL,
APELLIDO_PERSONAL VARCHAR(100) NULL,
CORREO VARCHAR(80) NULL,
TELEFONO VARCHAR(90) NULL,
COD_USUARIO VARCHAR(5) UNIQUE, 
FOREIGN KEY (COD_USUARIO) REFERENCES T_USUARIO(COD_USUARIO)
)